<?php

namespace app\controller;

use app\model\HomeTokenModel;
use app\model\UserModel;    
use app\controller\common\LogHelper;
use app\BaseController;
use think\facade\Lang;

class Base extends BaseController
{
    public static $user;

    public function initialize()
    {
        $this->user_info();
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function user_info()
    {
        $token = $this->request->header('x-csrf-token');
        if (empty($token)) $token = $this->request->post('token');
        if (empty($token)) return show([], 505, 'token不存在');
        $res = HomeTokenModel::auth_token($token); //查询token

        //查询当前用户信息
        $user_info = UserModel::page_one($res['user_id']);

        if (empty($user_info) || $user_info['status'] != 1) return show([], 503, '用户异常');
        
        $res['token'] = $token;
        //查询用户洗马什么的信息
        $lang = $this->request->param('lang','zh-cn');
        if ($lang == 'jpn') $lang ='jp';
        Lang::load(app()->getRootPath().'/app/lang/'.$lang.'.php');
        self::$user = $user_info;

    }

}