<?php
use think\facade\Route;

// 获取露珠列表数据
Route::rule('sicbo/get_table/get_data$', '/game.GetForeignTableInfo/get_lz_list');
// 获取荷官端露珠数据
Route::rule('sicbo/get_table/get_hg_data$', '/game.GetForeignTableInfo/get_hg_lz_list');
// 获取电投端露珠数据
Route::rule('api/diantou/table/getData', '/game.GetForeignTableInfo/get_hg_data_list');
// 获取电投端视频流地址
Route::rule('api/diantou/table/getTableVideo', '/game.GetForeignTableInfo/get_hg_video_list');
// 获取台桌视频流信息
Route::rule('sicbo/get_table/get_table_video', '/game.GetForeignTableInfo/get_table_video');
// 获取台桌列表
Route::rule('sicbo/get_table/list$', '/game.GetForeignTableInfo/get_table_list');
// 获取台桌统计信息（庄闲和次数等）
Route::rule('sicbo/get_table/get_table_count$', '/game.GetForeignTableInfo/get_table_count');
// 获取当前台桌详细信息（靴号、铺号等）
Route::rule('sicbo/get_table/table_info$', '/game.GetForeignTableInfo/get_table_info');
// 获取单个用户详细信息 
Route::rule('sicbo/user/info$', '/game.GetForeignTableInfo/get_user_info');
// 荷官手动开牌设置露珠数据
Route::rule('sicbo/get_table/post_data$', '/game.GetForeignTableInfo/set_post_data');
// 发送开局信号（开始投注倒计时）
Route::rule('sicbo/start/signal$', '/game.GetForeignTableInfo/set_start_signal');
// 发送结束信号（停止投注）
Route::rule('sicbo/end/signal$', '/game.GetForeignTableInfo/set_end_signal');
// 设置洗牌状态
Route::rule('sicbo/get_table/wash_brand$', '/game.GetForeignTableInfo/get_table_wash_brand');
// 手动设置靴号（新一轮游戏开始）
Route::rule('sicbo/get_table/add_xue$', '/game.GetForeignTableInfo/set_xue_number');
// 删除指定露珠记录
Route::rule('sicbo/get_table/clear_lu_zhu$', '/game.GetForeignTableInfo/lz_delete');
// 清空指定台桌的所有露珠记录
Route::rule('sicbo/get_table/clear_lu_zhu_one_table$', '/game.GetForeignTableInfo/lz_table_delete');
// 获取扑克牌详细信息
Route::rule('sicbo/pai/info$', '/game.GetForeignTableInfo/get_pai_info');
// 获取当前台桌详细信息（全部信息）
Route::rule('sicbo/table/info$', '/game.GetForeignTableInfo/get_table_info_for_bet');
// 获取用户投注历史记录
Route::rule('sicbo/bet/history$', '/game.GameInfo/get_user_bet_history');
// 获取投注记录详情
Route::rule('sicbo/bet/detail/(\d+)$', '/game.GameInfo/get_bet_detail');
// 获取指定露珠的扑克牌型信息
Route::rule('sicbo/game/poker$', '/game.GameInfo/get_poker_type');
// 用户下注接口
Route::rule('sicbo/bet/order$', '/order.Order/user_bet_order');
// 获取用户当前投注记录
Route::rule('sicbo/current/record$', '/order.Order/order_current_record');
// 首页路由
Route::rule('/$', '/index/index');

